language: node_js
node_js:
  - "8.9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database politico; CREATE TABLE IF NOT EXISTS users( id SERIAL PRIMARY KEY, firstname VARCHAR NOT NULL, lastname VARCHAR NOT NULL, othername VARCHAR NOT NULL, email VARCHAR(50) NOT NULL PRIMARY KEY, phonenumber VARCHAR(50) NOT NULL,passporturl text NOT NULL, isadmin BOOLEAN NOT NULL, password TEXT NOT NULL);CREATE TABLE IF NOT EXISTS office( office VARCHAR NOT NULL, name VARCHAR(200) NOT NULL, email VARCHAR(250) NOT NULL REFERENCES users(email))' -U postgres

after_success:
 - npm run coverage
